# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd FizzbuzzRacingWeb
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/FizzBuzzRacingWeb/Dist'
    artifact: 'app'
    publishLocation: 'pipeline'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Premium with MSDN(1d3a1693-db2c-4afb-b91b-fc4f1154af42)'
    appType: 'webAppLinux'
    WebAppName: 'FizzBuzzRacingWeb'
    deployToSlotOrASE: true
    ResourceGroupName: 'FizzBuzzRacing'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|12-lts'
    StartupCommand: 'ng build --prod'
